# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-26 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_auto_20190626_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=32)),
                ('ISBN', models.CharField(max_length=32)),
                ('publisher', models.CharField(max_length=32)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('pages', models.IntegerField(null=True)),
                ('describle', models.TextField(null=True)),
                ('position', models.CharField(max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
