# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-27 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0003_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('fine', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('WAITFORCHECK', 'WAITFORCHECK'), ('BORROWED', 'BORROWED'), ('RETURNED', 'RETURNED'), ('TURNDOWN', 'TURNDOWN'), ('DEMAGE', 'DEMAGE')], default='WAITFORCHECK', max_length=16)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsApp.Book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsApp.Readers')),
            ],
        ),
    ]
