# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-27 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_auto_20190627_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='fine',
            field=models.IntegerField(),
        ),
    ]
