# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-29 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0006_auto_20190627_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateField(auto_now_add=True)),
                ('end_time', models.DateField(auto_now_add=True)),
                ('total_fine', models.IntegerField(null=True)),
                ('reader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsApp.Readers')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='fine',
            field=models.IntegerField(default=20),
        ),
    ]
